### ISSUE TITLE
Autoplay is not supported

### ISSUE THREAD

**Issue by cutme** [blakewilson/vidbg#11]
Sometimes In Chrome and Safari I see error "Autoplay is not supported", it's a random error.. How can I prevent this?

**Comment by blakewilson** [comment]
Hi @cutme 

You will see the `Autoplay is not supported` error when the browser does not support or allow Autoplay. This could be anything from the browser just flat out not having support for Autoplay, but most of the time, because the browser has settings to disable autoplaying video. For Example, most browsers now a days require you to have the video `muted` to be autoplayed. If the video is not muted, you would get this error.

https://github.com/blakewilson/vidbg/blob/master/src/vidbg.js#L157

I realize this error is kind of vague. I think adding the actual exception message would be helpful.

**Comment by jacklinwood** [comment]
Hi Blake,

Great plugin BTW :)

I am aware of the autoplay issue in Safari if the video is not muted. The default option is for the video to be muted but when inspecting the element, I can see that muted is not being added therefore it isn't working in Safari.

Any ideas?
